<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
	<title><?= Lang::__DASHBOARD; ?></title>
	<style>
		#container
		{
			width: 500px;
			margin: 10px auto;
			background-color: #fff;
			color: #333;
			border: 1px solid gray;
			line-height: 130%;
		}
		
		a {
			text-decoration: none;
			color: #000080;
		}
		a:hover {
			color: #000;
			text-decoration: underline;
		}
		
		#top
		{
			padding: .5em;
			background-color: #ddd;
			border-bottom: 1px solid gray;
		}
		
		#top h1
		{
			padding: 0;
			margin: 0;
		}
		
		#leftnav
		{
			float: left;
			width: 160px;
			margin: 0;
			padding: 1em;
		}
		
		#leftnav ul
		{
			padding-left:5px;
		}
		
		#content
		{
			padding: 0.5em;
		}
		
		#footer
		{
			clear: both;
			margin: 0;
			padding: .5em;
			color: #333;
			background-color: #ddd;
			border-top: 1px solid gray;
		}
		
		#leftnav p { margin: 0 0 1em 0; }
		#content h2 { margin: 0 0 .5em 0; }
	</style>
</head>

<body>

<div id="container">

	<div id="top">
		<h1><?= Lang::__DASHBOARD; ?></h1>
	</div>
	
	
	<div id="content">
	
		<form action="<?= base_url() ?>dashboard/member/login" name="frmAction" method="POST">
		
		<table width="100%" border="0" cellpadding="1" cellspacing="1">
			<tr>
				<td width="35%" align="right">Username : &nbsp;
				<td><input type="text" name="username" value="" size="30">
			</tr>
			<tr>
				<td align="right">Password : &nbsp;
				<td><input type="password" name="password" value="" size="30">
			</tr>
			<tr>
				<td>
				<td><br><input type="submit" name="submit" value="Submit">
			</tr>		
		</table>	
		
		</form>
		
	</div>
	
	<div id="footer">
		Powered By <a href="mailto:buivantienduc@yahoo.com">Bui Van Tien Duc</a>
	</div>

</div>

</body>
</html>
