<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<!--	<base href="http://localhost/mvc/" />-->
	<title><?php echo $title; ?></title>
	<link rel="stylesheet" href="<?= base_url(); ?>layouts/css/style.css">
	<link rel="stylesheet" href="<?= base_url(); ?>layouts/css/paging.css">
</head>

<body>

<div id="container">

<div id="top">
<h1>Bui Van Tien Duc</h1>
</div>

<div id="leftnav">
<ul>
<li><a href="<?= __BASE_URL ?>"><?= Lang::__HOME; ?></a></li>
<li><a href="<?= __BASE_URL ?>index/render"><?= Lang::__RENDER_ACTION; ?></a></li>
<li><a href="<?= __BASE_URL ?>paging/paginator"><?= Lang::__PAGING; ?></a></li>
<li><a href="<?= __BASE_URL ?>database"><?= Lang::__NORMAL_DATABASE; ?></a></li>
<li><a href="<?= __BASE_URL ?>database/model"><?= Lang::__MODEL_DATABASE; ?></a></li>
</ul>
</div>

<div id="content">
	<?php echo $content; ?>
</div>

<div id="footer">
	Powered By <a href="mailto:buivantienduc@yahoo.com">Bui Van Tien Duc</a>
</div>

</div>

</body>
</html>
