<h1><?= $title; ?></h1>

<?php
	// Make your db query here. Include $pages->limit as described in step 8.	(i.e. SELECT id,fname,lname FROM employees $pages->limit)
	echo "<br>";
	echo $pages->display_pages(); // Optional call which will display the page numbers after the results.
	echo $pages->display_jump_menu(); // Optional – displays the page jump menu
	echo $pages->display_items_per_page(); //Optional – displays the items per page menu
?>