

<div class="content">

	<div class="header">
		<div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i> Group</h1>
                        <h4>Group Permission !</h4>
                    </div>
        </div>		
	</div>

	<div class="container-fluid">
		<div class="row-fluid">

			<div class="btn-toolbar text-right">
				<a href="<?php echo base_url().'dashboard/group/add'; ?>" class="btn btn-primary"><i class="icon-plus"></i> New Group</a>			
			</div>
			
            <!-- BEGIN Main Content -->
			<div class="row-fluid">
                    <div class="span12">
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-table"></i> Big one</h3>
                                <div class="box-tool">
                                    <a href="#" data-action="collapse"><i class="icon-chevron-up"></i></a>
                                </div>
                            </div>
                            <div class="box-content">
                                <table class="table table-striped table-hover fill-head">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Group Name</th>
                                            <th>Level</th>
                                            <th class="text-center">Is Admin</th>
                                            <th style="width: 70px">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    
                                    <?php
                                    	$i = 1; 
                                    	foreach ($rsGroups as $rowGroup) :
                                    		$url_edit = base_url().'dashboard/group/edit/'.$rowGroup['id'];
	                                    	$url_delete = base_url().'dashboard/group/delete/'.$rowGroup['id'];
                                    ?>
                                    
                                        <tr>
                                            <td><?php echo $i; ?></td>
                                            <td><?php echo h($rowGroup['group_name']); ?></td>
                                            <td><?php echo h($rowGroup['level']); ?></td>
                                            <td class="text-center">
	                                            <?php if ($rowGroup['is_admin'] == 1) :?>
		                                            <span class="label label-success">A</span>
	                                            <?php endif; ?>
                                            </td>
                                            <td>
												<div class="btn-group">
								                    <a href="<?php echo $url_edit; ?>" title="" class="btn btn-small btn-gray"><i class="icon-edit"></i></a>
<!-- 								                    <a data-toggle="modal" href="#myModal" title="" class="btn btn-small btn-danger"><i class="icon-trash"></i></a> -->
								                    <a href="javascript:confimDelete('<?php echo $url_delete; ?>');" title="" class="btn btn-small btn-danger"><i class="icon-trash"></i></a>								                    
								                </div>                                            
                                            </td>
                                        </tr>
                                        
									<?php
											$i++;	 
										endforeach; 
									?>                                        
                                        
                                        
                                    </tbody>
                                </table>
                            
<!-- 								<div class="pagination text-left"> -->
<!--                                     <ul> -->
<!--                                         <li><a href="#">← Prev</a></li> -->
<!--                                         <li><a href="#">1</a></li> -->
<!--                                         <li><a href="#">2</a></li> -->
<!--                                         <li class="active"><a href="#">3</a></li> -->
<!--                                         <li><a href="#">4</a></li> -->
<!--                                         <li><a href="#">5</a></li> -->
<!--                                         <li><a href="#">6</a></li> -->
<!--                                         <li><a href="#">Next → </a></li> -->
<!--                                     </ul> -->
<!-- 	                            </div>                             -->
                            
                            </div>
                            
                        </div>
                    </div>
			</div>
			<!-- END Main Content -->
                			
			
		</div>
	</div>
</div>


