
                <!-- BEGIN Page Title -->
                <div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i> Blank Page</h1>
                        <h4>You can start your customization from this one!</h4>
                    </div>
                </div>
                <!-- END Page Title -->

                <!-- BEGIN Breadcrumb -->
                <div id="breadcrumbs">
                    <ul class="breadcrumb">
                        <li>
                            <i class="icon-home"></i>
                            <a href="index.html">Home</a>
                            <span class="divider"><i class="icon-angle-right"></i></span>
                        </li>
                        <li class="active">Blank Page</li>
                    </ul>
                </div>
                <!-- END Breadcrumb -->

                <!-- BEGIN Main Content -->
                <div class="row-fluid">
                    <div class="span12">
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-file"></i> Sample Box</h3>
                                <div class="box-tool">
                                    <a data-action="collapse" href="#"><i class="icon-chevron-up"></i></a>
                                    <a data-action="close" href="#"><i class="icon-remove"></i></a>
                                </div>
                            </div>
                            <div class="box-content">
                                                                
							    <ul data-tabs="tabs" class="nav nav-tabs" id="tabs">
							    
							    	<li class="active">
							    		<a data-toggle="tab" href="#tab_id_1">
							    			<i class="icon-cogs"></i>&nbsp;Group Data							    		</a>
							    	</li>
							    
							    							    
							    	<li>
							    		<a data-toggle="tab" href="#tab_id_2">
							    			<i class="icon-cogs"></i>&nbsp;Permission Data							    		</a>
							    	</li>
							    
							    							    
							    </ul>
							    
							    
<form method="POST" class="form-horizontal" action="<?php echo $link_url; ?>">
							    
							    <div style="overflow: hidden;" class="tab-content" id="my-tab-content">
							    															    
							        <div id="tab_id_1" class="tab-pane active">
							        

	                                    <div class="control-group">
	                                        <label class="control-label" for="textfield4">Group Name</label>
	                                        <div class="controls">
	                                            <input type="text" class="input-xxlarge" value="" id="group_name" name="group_name">
	                                        </div>
	                                    </div>
	                                    
									    
	                                    <div class="control-group">
	                                        <label class="control-label" for="textfield4">Level</label>
	                                        <div class="controls">
	                                            <input type="text" class="input-small" value="" id="level" name="level">
	                                            
	<!-- 											<blockquote> -->
	<!-- 			                                    <h6>The website title </h6> -->
	<!-- 			                                </blockquote> -->
				                                			                                                                            
	                                        </div>
	                                    </div>
	                                    
										<div class="control-group">
	                                       <label class="control-label"></label>
	                                       <div class="controls">
	                                          <label class="checkbox">
	                                            <input type="checkbox" id="is_admin" name="is_admin" value="1"> Is Administrator
	                                          </label>
	                                       </div>
	                                    </div>                                    
	                                    
	                                    <div class="form-actions">
	                                       <button class="btn btn-primary" type="submit"><i class="icon-ok"></i> Save</button>
	                                    </div>
                                    							            
							            
							        </div>
							        							    							    
									<div id="tab_id_2" class="tab-pane">
							        
							        
								<div id="accordion2" class="accordion accordion-separate">
                                    
<?php foreach ($arrAcls as $module => $rowModules) : ?>                                    
                                    
                                    <div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a href="#collapse_<?php echo $module; ?>" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">
                                                <?php echo h($module); ?>
                                            </a>
                                        </div>
                                        <div class="accordion-body in collapse" id="collapse_<?php echo $module; ?>" style="height: auto;">
                                            <div class="accordion-inner">
											<dl>
											
										<?php foreach ($rowModules as $controler => $rowController) : ?>											
	                                            <dt><?php echo h($controler); ?></dt>
	                                            <?php foreach ($rowController as $action) : ?>
	                                            <dd>
	                                            	<label class="checkbox">
	                                            		<input type="checkbox" name="permission[<?php echo $module.'_'.$controler.'_'.$action;  ?>]" value="1"> 
	                                            		<?php echo h($action); ?>
	                                          		</label>
	                                          	</dd>
	                                          	<?php endforeach; ?>
										<?php endforeach; ?>	                                          	
                                          	
                                          	</dl>
                                            </div>
                                        </div>
                                    </div>
<?php endforeach; ?>                                    
                                    
                                    
                                </div>							        
                                    							            
							            
							        </div>							        

							    </div>

</form>
							    
 								<script type="text/javascript"> 								
								    jQuery(document).ready(function ($) {
								        $('#tabs').tab();
								    });
								</script>                               
                            
                            </div>                            
                                
                                
                        </div>
                    </div>
                </div>
                <!-- END Main Content -->
                
