
                <!-- BEGIN Page Title -->
                <div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i> Blank Page</h1>
                        <h4>You can start your customization from this one!</h4>
                    </div>
                </div>
                <!-- END Page Title -->

                <!-- BEGIN Breadcrumb -->
                <div id="breadcrumbs">
                    <ul class="breadcrumb">
                        <li>
                            <i class="icon-home"></i>
                            <a href="index.html">Home</a>
                            <span class="divider"><i class="icon-angle-right"></i></span>
                        </li>
                        <li class="active">Blank Page</li>
                    </ul>
                </div>
                <!-- END Breadcrumb -->

                <!-- BEGIN Main Content -->
                <div class="row-fluid">
                    <div class="span12">
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-file"></i> Sample Box</h3>
                                <div class="box-tool">
                                    <a data-action="collapse" href="#"><i class="icon-chevron-up"></i></a>
                                    <a data-action="close" href="#"><i class="icon-remove"></i></a>
                                </div>
                            </div>
                            <div class="box-content">
                                

                            
								<div id="accordion2" class="accordion accordion-separate">
                                    <div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a href="#collapseOne" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">
                                                Collapsible Group Item #1
                                            </a>
                                        </div>
                                        <div class="accordion-body in collapse" id="collapseOne" style="height: auto;">
                                            <div class="accordion-inner">

                                     	<dl>
                                            <dt>Description lists</dt>
                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 1
                                          		</label>
                                          	</dd>
                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 2
                                          		</label>
                                          	</dd>
                                          	                                          	                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 3
                                          		</label>
                                          	</dd>
                                            <dt>Euismod</dt>
                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 1
                                          		</label>
                                          	</dd>
                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 2
                                          		</label>
                                          	</dd>
                                          	                                          	                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 3
                                          		</label>
                                          	</dd>
                                            <dt>Malesuada porta</dt>
                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 1
                                          		</label>
                                          	</dd>
                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 2
                                          		</label>
                                          	</dd>
                                          	                                          	                                            <dd>
                                            	<label class="checkbox">
                                            		<input type="checkbox" value=""> Checkbox 3
                                          		</label>
                                          	</dd>
                                        </dl>
                                                
                                                 
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a href="#collapseTwo" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">
                                                Collapsible Group Item #2
                                            </a>
                                        </div>
                                        <div class="accordion-body collapse" id="collapseTwo">
                                            <div class="accordion-inner">
                                                Anim pariatur cliche...Lorem ipsum Duis occaecat Excepteur est magna tempor ex ea enim sunt mollit proident. Lorem ipsum sed laboris ut adipisicing ut et aute occaecat aute enim occaecat. 
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a href="#collapseThree" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">
                                                Collapsible Group Item #3
                                            </a>
                                        </div>
                                        <div class="accordion-body collapse" id="collapseThree">
                                            <div class="accordion-inner">
                                                Anim pariatur cliche...Lorem ipsum do culpa adipisicing quis non nisi ullamco. Lorem ipsum velit dolore qui Excepteur fugiat et dolor proident reprehenderit magna aliqua enim consectetur nisi. Lorem ipsum sit laborum est magna veniam ex ut velit do aliqua amet dolore enim minim eu. Lorem ipsum adipisicing officia occaecat deserunt enim minim veniam sint amet sed consectetur nisi quis. 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                
                                
                                
                            </div>
                        </div>
                    </div>
                </div>
                <br><br><br><br><br><br><br><br><br><br><br><br>
                <br><br><br><br><br><br><br><br><br><br><br><br>
                <!-- END Main Content -->
                
