<!--
	Website generated by CMS v02
	URL: http://demo.sofresh.vn
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="css/common.css" />
<link rel="icon" href="../favicon.gif" type="image/x-icon" />
<title>CMS - {web_client}</title> 
<link rel="icon" href="favicon.png" type="image/png" /> 
      
<script type="text/javascript" src="../plugins/jquery.js"></script>
<script>var plugins_dir = '../';var root_dir = '{root_dir}'; var lang = '{system.lang}';</script>
<script type="text/javascript" src="../plugins/tableorder/jquery.tableorder.js"></script>
<script type="text/javascript" src="js/common.js"></script>
<script type="text/javascript" src="js/module.configure.js"></script>

<script type="text/javascript" src="../plugins/divbox/divbox.js"></script>
<link rel="stylesheet" href="../plugins/divbox/css/frontend.css" type="text/css" media="screen" />
<script type="text/javascript">
var access_new = '{access.new}';
var access_edit = '{access.edit}{action_update_check}';
var access_delete = '{access.delete}';
</script>
<script type="text/javascript" src="../plugins/validate/validate.js"></script>
<link rel="stylesheet" href="../plugins/validate/css/validate.css" type="text/css" media="screen" />
<script type="text/javascript" src="../plugins/dateinput/dateinput.js"></script>

<!--<script type="text/javascript" src="js/googlemap.js"></script>-->