<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<!--	<base href="http://localhost/mvc/" />-->
	<title><?php echo $title; ?></title>
	<link rel="stylesheet" href="<?= __CSS_URL; ?>style.css">
	<link rel="stylesheet" href="<?= __CSS_URL; ?>paging.css">
</head>

<body>

<div id="container">

<div id="top">
<h1>Simple MVC Framework</h1>
</div>

<div id="leftnav">
<ul>
<li><a href="<?= __BASE_URL ?>"><?= Lang::__HOME; ?></a></li>
<li><a href="<?= __BASE_URL ?>site/home/render"><?= Lang::__RENDER_ACTION; ?></a></li>
<li><a href="<?= __BASE_URL ?>paging/page/paginator"><?= Lang::__PAGING; ?></a></li>
<li><a href="<?= __BASE_URL ?>database/model"><?= Lang::__NORMAL_DATABASE; ?></a></li>
<li><a href="<?= __BASE_URL ?>database/model/model"><?= Lang::__MODEL_DATABASE; ?></a></li>
<li><a href="<?= __BASE_URL ?>pdo-database/pdo-model"><?= Lang::__PDO_MODEL_DATABASE; ?></a></li>
<li><a href="<?= __BASE_URL ?>active-record/active-record"><?= Lang::__AR_DATABASE; ?></a></li>
</ul>
</div>

<div id="content">
	<?php echo $main_content; ?>
</div>

<div id="footer">
	Powered By <a href="mailto:buivantienduc@yahoo.com">Bui Van Tien Duc</a>
</div>

</div>

</body>
</html>
